language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t hesmondjeet/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true hesmondjeet/react-test npm test

after_success: 
  - docker build -t hesmondjeet/multi-client -f ./client
  - docker build -t hesmondjeet/multi-nginx -f ./nginx
  - docker build -t hesmondjeet/multi-server -f ./server
  - docker build -t hesmondjeet/multi-worker -f ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hesmondjeet/multi-client
  - docker push hesmondjeet/multi-nginx
  - docker push hesmondjeet/multi-server
  - docker push hesmondjeet/multi-worker
