language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t hesmondjeet/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run hesmondjeet/react-test npm test -- --coverage

after_success: 
  - docker build -t hesmondjeet/multi-client -f ./client
  - docker build -t hesmondjeet/multi-nginx -f ./nginx
  - docker build -t hesmondjeet/multi-server -f ./server
  - docker build -t hesmondjeet/multi-worker -f ./worker

# script:
#   - docker run -e CI=true USERNAME/react-test npm test